spring.application.name=hackyeah-2026-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hackyeah}
spring.datasource.username=${DB_USER:hackyeah}
spring.datasource.password=${DB_PASSWORD:hackyeah}
spring.jpa.hibernate.ddl-auto=update
